{% set name = "titus2" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd7ca43e2a7cde530e0ae440cb65d87aac9eedd8cdba9c47cff5d1882e88c297

build:
  skip: True  # [py>=310]
  # missing win build for avro --> avro-python3
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >=1.15.0,<1.20.0
    - avro-python3 >=1.8.2
    - ply >=3.11
    - pyyaml >=5.1.2
    - pytz >=2019.1

test:
  imports:
    - titus
    - titus.producer
    - titus.lib
    - titus.lib.model
    - titus.lib.prob
    - titus.lib.stat
    - titus.inspector
  requires:
    - pip
  source_files:
    - test
  commands:
    - pip check
    - python -m unittest discover -s test -p "test*.py"

about:
  home: https://realworldpython.github.io/titus2
  summary: Python 3 implementation of Portable Format for Analytics
  description: |
    Titus 2 is a fork of the original Titus python library which resides in the (now defunct) Hadrian repository. Titus
    is not actively maintained by the Open Data Group and only supports Python 2, so this fork was created to actively
    support its development for Python 3.
  license: Apache-2.0
  license_file: LICENSE
  license_family: APACHE
  doc_url: https://realworldpython.github.io/titus2
  dev_url: https://github.com/animator/titus2

extra:
  recipe-maintainers:
    - boldorider4
